---

- name: Demo
  hosts: all
  become: yes
  pre_tasks:
      
  - name: Install Updates Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

...
