---

- name: Install MySQL
  apt:
    pkg:
      - python3-mysqldb
      - mysql-server

- name: Start MySQL Service
  service: name=mysql state=started enabled=yes
  
- name: Update MySQL Password
  mysql_user:
    name: root
    host: "{{item}}"
    password: "{{mysql_root_password}}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - laravel
    - 127.0.0.1
    - ::1
    - localhost